# Permalinks
permalink:   pretty

# Settings
markdown:    kramdown
destination: ./_gh_pages
exclude:     ["README.md"]
paginate:    5
encoding:    UTF-8
future:      false
name:        Odin Expo
url:         http://expo.wpod.in
description: "Projetos desenvolvidos com Odin Framework"
